"""Render an evaluate-stage result into a human-readable markdown report.

Usage: python -m sdf report runs/<id>/output/stage_evaluate.json [--out docs/results.md]

Pure text transformation - no torch, fully unit-testable. The report is the
project's evidence artifact: what was measured, on which commit, with which
data, and what the honest aggregate says.
"""

from __future__ import annotations

import json
from pathlib import Path

RARE_CLASSES = ("akiec", "bcc", "df", "vasc")


def _fmt_spread(spread: dict) -> str:
    mean, std = spread["mean"], spread["std"]
    sign = "+" if mean >= 0 else ""
    return f"{sign}{mean:.4f} ± {std:.4f}"


def render(evaluate_result: dict, *, context: dict | None = None) -> str:
    """Build the markdown report from a stage_evaluate.json payload."""
    metrics = evaluate_result.get("metrics", {})
    arms = metrics.get("arms", {})
    aggregate = metrics.get("aggregate")
    context = context or {}

    lines: list[str] = []
    lines.append("# Synthetic-data augmentation: measured results")
    lines.append("")
    if context:
        lines.append("| | |")
        lines.append("|---|---|")
        for key, value in context.items():
            lines.append(f"| {key} | {value} |")
        lines.append("")

    lines.append(f"Test set: **{metrics.get('test_n', '?')} real images** "
                 "(never touched by generation or model selection).")
    lines.append("")

    # --- arms table --------------------------------------------------------
    lines.append("## Arms")
    lines.append("")
    lines.append("| arm | macro-F1 | accuracy | train real | train synthetic |")
    lines.append("|---|---|---|---|---|")
    for tag in sorted(arms):
        arm = arms[tag]
        sources = arm.get("train_sources") or {}
        lines.append(
            f"| {tag} | {arm['macro_f1']:.4f} | {arm['accuracy']:.4f} "
            f"| {sources.get('real', '?')} | {sources.get('synthetic', '?')} |"
        )
    lines.append("")

    # --- aggregate ---------------------------------------------------------
    if aggregate:
        n = aggregate["n_pairs"]
        lines.append(f"## Paired deltas (augmented − real-only), mean ± std over {n} seed(s)")
        lines.append("")
        summary = aggregate["summary"]
        lines.append(f"- **macro-F1: {_fmt_spread(summary['macro_f1_delta'])}**")
        lines.append(f"- **accuracy: {_fmt_spread(summary['accuracy_delta'])}**")
        lines.append("")
        lines.append("Per-class (rare classes are the augmentation targets):")
        lines.append("")
        lines.append("| class | rare | recall Δ | F1 Δ |")
        lines.append("|---|---|---|---|")
        for cls, deltas in sorted(aggregate["per_class"].items()):
            rare = "**yes**" if cls in RARE_CLASSES else "no"
            lines.append(
                f"| {cls} | {rare} | {_fmt_spread(deltas['recall_delta'])} "
                f"| {_fmt_spread(deltas['f1_delta'])} |"
            )
        lines.append("")
        lines.append(
            "A delta is only meaningful when its magnitude clearly exceeds its "
            "spread and the class's per-image quantum (1/support)."
        )
    else:
        for key in metrics:
            if key.startswith("deltas_vs_"):
                lines.append(f"## Deltas ({key.removeprefix('deltas_vs_')} baseline)")
                lines.append("")
                lines.append("```json")
                lines.append(json.dumps(metrics[key], indent=1, sort_keys=True))
                lines.append("```")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by `python -m sdf report`. Full artifacts under the "
                 "run directory named above; every synthetic image is tracked in "
                 "`synthetic_manifest.jsonl` with `synthetic: true`.*")
    return "\n".join(lines) + "\n"


def build_report(evaluate_json: Path, out_path: Path, context: dict | None = None) -> Path:
    data = json.loads(evaluate_json.read_text(encoding="utf-8"))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render(data, context=context), encoding="utf-8")
    return out_path
